# coding: utf-8

"""
    CyberSource Merged Spec

    All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import CyberSource
from CyberSource.rest import ApiException
from CyberSource.models.tms_error_response import TMSErrorResponse


class TestTMSErrorResponse(unittest.TestCase):
    """ TMSErrorResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTMSErrorResponse(self):
        """
        Test TMSErrorResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = CyberSource.models.tms_error_response.TMSErrorResponse()
        pass


if __name__ == '__main__':
    unittest.main()
