# coding: utf-8

"""
    CyberSource Merged Spec

    All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import os
import sys
import unittest

import CyberSource
from CyberSource.rest import ApiException
from CyberSource.models.merchant_registration_validation_error_response422 import MerchantRegistrationValidationErrorResponse422


class TestMerchantRegistrationValidationErrorResponse422(unittest.TestCase):
    """ MerchantRegistrationValidationErrorResponse422 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMerchantRegistrationValidationErrorResponse422(self):
        """
        Test MerchantRegistrationValidationErrorResponse422
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = CyberSource.models.merchant_registration_validation_error_response422.MerchantRegistrationValidationErrorResponse422()
        pass


if __name__ == '__main__':
    unittest.main()
