# coding: utf-8

"""
    CyberSource Merged Spec

    All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import os
import sys
import unittest

import CyberSource
from CyberSource.rest import ApiException
from CyberSource.models.get_subscription_response1_links import GetSubscriptionResponse1Links


class TestGetSubscriptionResponse1Links(unittest.TestCase):
    """ GetSubscriptionResponse1Links unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSubscriptionResponse1Links(self):
        """
        Test GetSubscriptionResponse1Links
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = CyberSource.models.get_subscription_response1_links.GetSubscriptionResponse1Links()
        pass


if __name__ == '__main__':
    unittest.main()
