# coding: utf-8

"""
    CyberSource Flex API

    Simple PAN tokenization service

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import CyberSource
from CyberSource.rest import ApiException
from CyberSource.models.inline_response_200_2_order_information_line_items import InlineResponse2002OrderInformationLineItems


class TestInlineResponse2002OrderInformationLineItems(unittest.TestCase):
    """ InlineResponse2002OrderInformationLineItems unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2002OrderInformationLineItems(self):
        """
        Test InlineResponse2002OrderInformationLineItems
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = CyberSource.models.inline_response_200_2_order_information_line_items.InlineResponse2002OrderInformationLineItems()
        pass


if __name__ == '__main__':
    unittest.main()
