# coding: utf-8

"""
    CyberSource Merged Spec

    All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import os
import sys
import unittest

import CyberSource
from CyberSource.rest import ApiException
from CyberSource.models.kms_v2_keys_asym_post201_response import KmsV2KeysAsymPost201Response


class TestKmsV2KeysAsymPost201Response(unittest.TestCase):
    """ KmsV2KeysAsymPost201Response unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKmsV2KeysAsymPost201Response(self):
        """
        Test KmsV2KeysAsymPost201Response
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = CyberSource.models.kms_v2_keys_asym_post201_response.KmsV2KeysAsymPost201Response()
        pass


if __name__ == '__main__':
    unittest.main()
