# coding: utf-8

"""
    CyberSource Merged Spec

    All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import os
import sys
import unittest

import CyberSource
from CyberSource.rest import ApiException
from CyberSource.models.inline_response2014_payloads import InlineResponse2014Payloads


class TestInlineResponse2014Payloads(unittest.TestCase):
    """ InlineResponse2014Payloads unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2014Payloads(self):
        """
        Test InlineResponse2014Payloads
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = CyberSource.models.inline_response2014_payloads.InlineResponse2014Payloads()
        pass


if __name__ == '__main__':
    unittest.main()
