# coding: utf-8

"""
    CyberSource Merged Spec

    All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import CyberSource
from CyberSource.rest import ApiException
from CyberSource.models.ptsv2payments_travel_information_auto_rental_rental_address import Ptsv2paymentsTravelInformationAutoRentalRentalAddress


class TestPtsv2paymentsTravelInformationAutoRentalRentalAddress(unittest.TestCase):
    """ Ptsv2paymentsTravelInformationAutoRentalRentalAddress unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPtsv2paymentsTravelInformationAutoRentalRentalAddress(self):
        """
        Test Ptsv2paymentsTravelInformationAutoRentalRentalAddress
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = CyberSource.models.ptsv2payments_travel_information_auto_rental_rental_address.Ptsv2paymentsTravelInformationAutoRentalRentalAddress()
        pass


if __name__ == '__main__':
    unittest.main()
