# coding: utf-8

"""
    CyberSource Flex API

    Simple PAN tokenization service

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import CyberSource
from CyberSource.rest import ApiException
from CyberSource.models.v2payments_aggregator_information import V2paymentsAggregatorInformation


class TestV2paymentsAggregatorInformation(unittest.TestCase):
    """ V2paymentsAggregatorInformation unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV2paymentsAggregatorInformation(self):
        """
        Test V2paymentsAggregatorInformation
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = CyberSource.models.v2payments_aggregator_information.V2paymentsAggregatorInformation()
        pass


if __name__ == '__main__':
    unittest.main()
