# coding: utf-8

"""
    CyberSource Flex API

    Simple PAN tokenization service

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import CyberSource
from CyberSource.rest import ApiException
from CyberSource.models.v2payouts_processing_information import V2payoutsProcessingInformation


class TestV2payoutsProcessingInformation(unittest.TestCase):
    """ V2payoutsProcessingInformation unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV2payoutsProcessingInformation(self):
        """
        Test V2payoutsProcessingInformation
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = CyberSource.models.v2payouts_processing_information.V2payoutsProcessingInformation()
        pass


if __name__ == '__main__':
    unittest.main()
