# coding: utf-8

"""
    CyberSource Merged Spec

    All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import CyberSource
from CyberSource.rest import ApiException
from CyberSource.models.ptsv2payments_payment_information_direct_debit_mandate import Ptsv2paymentsPaymentInformationDirectDebitMandate


class TestPtsv2paymentsPaymentInformationDirectDebitMandate(unittest.TestCase):
    """ Ptsv2paymentsPaymentInformationDirectDebitMandate unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPtsv2paymentsPaymentInformationDirectDebitMandate(self):
        """
        Test Ptsv2paymentsPaymentInformationDirectDebitMandate
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = CyberSource.models.ptsv2payments_payment_information_direct_debit_mandate.Ptsv2paymentsPaymentInformationDirectDebitMandate()
        pass


if __name__ == '__main__':
    unittest.main()
