# coding: utf-8

"""
    CyberSource Flex API

    Simple PAN tokenization service

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import CyberSource
from CyberSource.rest import ApiException
from CyberSource.models.inline_response_201__embedded_capture__links import InlineResponse201EmbeddedCaptureLinks


class TestInlineResponse201EmbeddedCaptureLinks(unittest.TestCase):
    """ InlineResponse201EmbeddedCaptureLinks unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse201EmbeddedCaptureLinks(self):
        """
        Test InlineResponse201EmbeddedCaptureLinks
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = CyberSource.models.inline_response_201__embedded_capture__links.InlineResponse201EmbeddedCaptureLinks()
        pass


if __name__ == '__main__':
    unittest.main()
