# coding: utf-8

"""
    CyberSource Merged Spec

    All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import os
import sys
import unittest

import CyberSource
from CyberSource.rest import ApiException
from CyberSource.models.inline_response20113_order import InlineResponse20113Order


class TestInlineResponse20113Order(unittest.TestCase):
    """ InlineResponse20113Order unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20113Order(self):
        """
        Test InlineResponse20113Order
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = CyberSource.models.inline_response20113_order.InlineResponse20113Order()
        pass


if __name__ == '__main__':
    unittest.main()
