# coding: utf-8

"""
    CyberSource Flex API

    Simple PAN tokenization service

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import CyberSource
from CyberSource.rest import ApiException
from CyberSource.models.v2payments_processing_information_issuer import V2paymentsProcessingInformationIssuer


class TestV2paymentsProcessingInformationIssuer(unittest.TestCase):
    """ V2paymentsProcessingInformationIssuer unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV2paymentsProcessingInformationIssuer(self):
        """
        Test V2paymentsProcessingInformationIssuer
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = CyberSource.models.v2payments_processing_information_issuer.V2paymentsProcessingInformationIssuer()
        pass


if __name__ == '__main__':
    unittest.main()
