# coding: utf-8

"""
    CyberSource Merged Spec

    All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from pprint import pformat
from six import iteritems
import re


class Acpv1mppcredentialsChallengeEncryptionJwk(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'kty': 'str',
        'kid': 'str',
        'use': 'str',
        'alg': 'str',
        'n': 'str',
        'e': 'str'
    }

    attribute_map = {
        'kty': 'kty',
        'kid': 'kid',
        'use': 'use',
        'alg': 'alg',
        'n': 'n',
        'e': 'e'
    }

    def __init__(self, kty=None, kid=None, use=None, alg=None, n=None, e=None):
        """
        Acpv1mppcredentialsChallengeEncryptionJwk - a model defined in Swagger
        """

        self._kty = None
        self._kid = None
        self._use = None
        self._alg = None
        self._n = None
        self._e = None

        self.kty = kty
        self.kid = kid
        self.use = use
        self.alg = alg
        self.n = n
        self.e = e

    @property
    def kty(self):
        """
        Gets the kty of this Acpv1mppcredentialsChallengeEncryptionJwk.
        Key type. MUST be 'RSA'.

        :return: The kty of this Acpv1mppcredentialsChallengeEncryptionJwk.
        :rtype: str
        """
        return self._kty

    @kty.setter
    def kty(self, kty):
        """
        Sets the kty of this Acpv1mppcredentialsChallengeEncryptionJwk.
        Key type. MUST be 'RSA'.

        :param kty: The kty of this Acpv1mppcredentialsChallengeEncryptionJwk.
        :type: str
        """

        self._kty = kty

    @property
    def kid(self):
        """
        Gets the kid of this Acpv1mppcredentialsChallengeEncryptionJwk.
        Key ID. Identifies the key within a JWKS.

        :return: The kid of this Acpv1mppcredentialsChallengeEncryptionJwk.
        :rtype: str
        """
        return self._kid

    @kid.setter
    def kid(self, kid):
        """
        Sets the kid of this Acpv1mppcredentialsChallengeEncryptionJwk.
        Key ID. Identifies the key within a JWKS.

        :param kid: The kid of this Acpv1mppcredentialsChallengeEncryptionJwk.
        :type: str
        """

        self._kid = kid

    @property
    def use(self):
        """
        Gets the use of this Acpv1mppcredentialsChallengeEncryptionJwk.
        Public key use. MUST be 'enc'.

        :return: The use of this Acpv1mppcredentialsChallengeEncryptionJwk.
        :rtype: str
        """
        return self._use

    @use.setter
    def use(self, use):
        """
        Sets the use of this Acpv1mppcredentialsChallengeEncryptionJwk.
        Public key use. MUST be 'enc'.

        :param use: The use of this Acpv1mppcredentialsChallengeEncryptionJwk.
        :type: str
        """

        self._use = use

    @property
    def alg(self):
        """
        Gets the alg of this Acpv1mppcredentialsChallengeEncryptionJwk.
        Algorithm. MUST be 'RSA-OAEP-256'.

        :return: The alg of this Acpv1mppcredentialsChallengeEncryptionJwk.
        :rtype: str
        """
        return self._alg

    @alg.setter
    def alg(self, alg):
        """
        Sets the alg of this Acpv1mppcredentialsChallengeEncryptionJwk.
        Algorithm. MUST be 'RSA-OAEP-256'.

        :param alg: The alg of this Acpv1mppcredentialsChallengeEncryptionJwk.
        :type: str
        """

        self._alg = alg

    @property
    def n(self):
        """
        Gets the n of this Acpv1mppcredentialsChallengeEncryptionJwk.
        RSA modulus (Base64urlUInt-encoded per RFC 7518 Section 6.3.1.1).

        :return: The n of this Acpv1mppcredentialsChallengeEncryptionJwk.
        :rtype: str
        """
        return self._n

    @n.setter
    def n(self, n):
        """
        Sets the n of this Acpv1mppcredentialsChallengeEncryptionJwk.
        RSA modulus (Base64urlUInt-encoded per RFC 7518 Section 6.3.1.1).

        :param n: The n of this Acpv1mppcredentialsChallengeEncryptionJwk.
        :type: str
        """

        self._n = n

    @property
    def e(self):
        """
        Gets the e of this Acpv1mppcredentialsChallengeEncryptionJwk.
        RSA public exponent (Base64urlUInt-encoded per RFC 7518 Section 6.3.1.2).

        :return: The e of this Acpv1mppcredentialsChallengeEncryptionJwk.
        :rtype: str
        """
        return self._e

    @e.setter
    def e(self, e):
        """
        Sets the e of this Acpv1mppcredentialsChallengeEncryptionJwk.
        RSA public exponent (Base64urlUInt-encoded per RFC 7518 Section 6.3.1.2).

        :param e: The e of this Acpv1mppcredentialsChallengeEncryptionJwk.
        :type: str
        """

        self._e = e

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Acpv1mppcredentialsChallengeEncryptionJwk):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
