# coding: utf-8

"""
    CyberSource Merged Spec

    All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from pprint import pformat
from six import iteritems
import re


class AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_correlation_id': 'str',
        'instruction_id': 'str',
        'status': 'str',
        'authorization': 'str',
        'signed_payload': 'str'
    }

    attribute_map = {
        'client_correlation_id': 'clientCorrelationId',
        'instruction_id': 'instructionId',
        'status': 'status',
        'authorization': 'authorization',
        'signed_payload': 'signedPayload'
    }

    def __init__(self, client_correlation_id=None, instruction_id=None, status=None, authorization=None, signed_payload=None):
        """
        AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete - a model defined in Swagger
        """

        self._client_correlation_id = None
        self._instruction_id = None
        self._status = None
        self._authorization = None
        self._signed_payload = None

        self.client_correlation_id = client_correlation_id
        self.instruction_id = instruction_id
        if status is not None:
          self.status = status
        if authorization is not None:
          self.authorization = authorization
        if signed_payload is not None:
          self.signed_payload = signed_payload

    @property
    def client_correlation_id(self):
        """
        Gets the client_correlation_id of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        Client Correlation Id used during the tokenization or during FIDO assertion.

        :return: The client_correlation_id of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        :rtype: str
        """
        return self._client_correlation_id

    @client_correlation_id.setter
    def client_correlation_id(self, client_correlation_id):
        """
        Sets the client_correlation_id of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        Client Correlation Id used during the tokenization or during FIDO assertion.

        :param client_correlation_id: The client_correlation_id of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        :type: str
        """

        self._client_correlation_id = client_correlation_id

    @property
    def instruction_id(self):
        """
        Gets the instruction_id of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        Instruction identifier.

        :return: The instruction_id of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        :rtype: str
        """
        return self._instruction_id

    @instruction_id.setter
    def instruction_id(self, instruction_id):
        """
        Sets the instruction_id of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        Instruction identifier.

        :param instruction_id: The instruction_id of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        :type: str
        """

        self._instruction_id = instruction_id

    @property
    def status(self):
        """
        Gets the status of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        Status of the Retrieve Payment Credentials request.

        :return: The status of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        Status of the Retrieve Payment Credentials request.

        :param status: The status of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        :type: str
        """

        self._status = status

    @property
    def authorization(self):
        """
        Gets the authorization of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        First Party Authorization Token/code.

        :return: The authorization of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        :rtype: str
        """
        return self._authorization

    @authorization.setter
    def authorization(self, authorization):
        """
        Sets the authorization of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        First Party Authorization Token/code.

        :param authorization: The authorization of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        :type: str
        """

        self._authorization = authorization

    @property
    def signed_payload(self):
        """
        Gets the signed_payload of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        Signed payload containing the payment credentials.

        :return: The signed_payload of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        :rtype: str
        """
        return self._signed_payload

    @signed_payload.setter
    def signed_payload(self, signed_payload):
        """
        Sets the signed_payload of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        Signed payload containing the payment credentials.

        :param signed_payload: The signed_payload of this AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete.
        :type: str
        """

        self._signed_payload = signed_payload

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AgenticRetrievePaymentCredentialsResponse200TransactionResponseComplete):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
