# coding: utf-8

"""
    CyberSource Merged Spec

    All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from pprint import pformat
from six import iteritems
import re


class Dmsv3devicesdeassociateDevices(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'device_id': 'str',
        'reason': 'str',
        'code': 'str'
    }

    attribute_map = {
        'device_id': 'deviceId',
        'reason': 'reason',
        'code': 'code'
    }

    def __init__(self, device_id=None, reason=None, code=None):
        """
        Dmsv3devicesdeassociateDevices - a model defined in Swagger
        """

        self._device_id = None
        self._reason = None
        self._code = None

        if device_id is not None:
          self.device_id = device_id
        if reason is not None:
          self.reason = reason
        if code is not None:
          self.code = code

    @property
    def device_id(self):
        """
        Gets the device_id of this Dmsv3devicesdeassociateDevices.

        :return: The device_id of this Dmsv3devicesdeassociateDevices.
        :rtype: str
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id):
        """
        Sets the device_id of this Dmsv3devicesdeassociateDevices.

        :param device_id: The device_id of this Dmsv3devicesdeassociateDevices.
        :type: str
        """

        self._device_id = device_id

    @property
    def reason(self):
        """
        Gets the reason of this Dmsv3devicesdeassociateDevices.

        :return: The reason of this Dmsv3devicesdeassociateDevices.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """
        Sets the reason of this Dmsv3devicesdeassociateDevices.

        :param reason: The reason of this Dmsv3devicesdeassociateDevices.
        :type: str
        """

        self._reason = reason

    @property
    def code(self):
        """
        Gets the code of this Dmsv3devicesdeassociateDevices.

        :return: The code of this Dmsv3devicesdeassociateDevices.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """
        Sets the code of this Dmsv3devicesdeassociateDevices.

        :param code: The code of this Dmsv3devicesdeassociateDevices.
        :type: str
        """

        self._code = code

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Dmsv3devicesdeassociateDevices):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
