# coding: utf-8

"""
    CyberSource Merged Spec

    All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from pprint import pformat
from six import iteritems
import re


class InlineResponse2011PayoutInformationPushFunds(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'money_transfer_fast_funds_cross_border': 'str',
        'money_transfer_fast_funds_domestic': 'str',
        'money_transfer_cross_border': 'str',
        'money_transfer_domestic': 'str',
        'non_money_transfer_fast_funds_cross_border': 'str',
        'non_money_transfer_fast_funds_domestic': 'str',
        'non_money_transfer_cross_border': 'str',
        'non_money_transfer_domestic': 'str',
        'online_gambling_fast_funds_cross_border': 'str',
        'online_gambling_fast_funds_domestic': 'str',
        'online_gambling_cross_border': 'str',
        'online_gambling_domestic': 'str',
        'domestic_participant': 'str',
        'cross_border_participant': 'str'
    }

    attribute_map = {
        'money_transfer_fast_funds_cross_border': 'moneyTransferFastFundsCrossBorder',
        'money_transfer_fast_funds_domestic': 'moneyTransferFastFundsDomestic',
        'money_transfer_cross_border': 'moneyTransferCrossBorder',
        'money_transfer_domestic': 'moneyTransferDomestic',
        'non_money_transfer_fast_funds_cross_border': 'nonMoneyTransferFastFundsCrossBorder',
        'non_money_transfer_fast_funds_domestic': 'nonMoneyTransferFastFundsDomestic',
        'non_money_transfer_cross_border': 'nonMoneyTransferCrossBorder',
        'non_money_transfer_domestic': 'nonMoneyTransferDomestic',
        'online_gambling_fast_funds_cross_border': 'onlineGamblingFastFundsCrossBorder',
        'online_gambling_fast_funds_domestic': 'onlineGamblingFastFundsDomestic',
        'online_gambling_cross_border': 'onlineGamblingCrossBorder',
        'online_gambling_domestic': 'onlineGamblingDomestic',
        'domestic_participant': 'domesticParticipant',
        'cross_border_participant': 'crossBorderParticipant'
    }

    def __init__(self, money_transfer_fast_funds_cross_border=None, money_transfer_fast_funds_domestic=None, money_transfer_cross_border=None, money_transfer_domestic=None, non_money_transfer_fast_funds_cross_border=None, non_money_transfer_fast_funds_domestic=None, non_money_transfer_cross_border=None, non_money_transfer_domestic=None, online_gambling_fast_funds_cross_border=None, online_gambling_fast_funds_domestic=None, online_gambling_cross_border=None, online_gambling_domestic=None, domestic_participant=None, cross_border_participant=None):
        """
        InlineResponse2011PayoutInformationPushFunds - a model defined in Swagger
        """

        self._money_transfer_fast_funds_cross_border = None
        self._money_transfer_fast_funds_domestic = None
        self._money_transfer_cross_border = None
        self._money_transfer_domestic = None
        self._non_money_transfer_fast_funds_cross_border = None
        self._non_money_transfer_fast_funds_domestic = None
        self._non_money_transfer_cross_border = None
        self._non_money_transfer_domestic = None
        self._online_gambling_fast_funds_cross_border = None
        self._online_gambling_fast_funds_domestic = None
        self._online_gambling_cross_border = None
        self._online_gambling_domestic = None
        self._domestic_participant = None
        self._cross_border_participant = None

        if money_transfer_fast_funds_cross_border is not None:
          self.money_transfer_fast_funds_cross_border = money_transfer_fast_funds_cross_border
        if money_transfer_fast_funds_domestic is not None:
          self.money_transfer_fast_funds_domestic = money_transfer_fast_funds_domestic
        if money_transfer_cross_border is not None:
          self.money_transfer_cross_border = money_transfer_cross_border
        if money_transfer_domestic is not None:
          self.money_transfer_domestic = money_transfer_domestic
        if non_money_transfer_fast_funds_cross_border is not None:
          self.non_money_transfer_fast_funds_cross_border = non_money_transfer_fast_funds_cross_border
        if non_money_transfer_fast_funds_domestic is not None:
          self.non_money_transfer_fast_funds_domestic = non_money_transfer_fast_funds_domestic
        if non_money_transfer_cross_border is not None:
          self.non_money_transfer_cross_border = non_money_transfer_cross_border
        if non_money_transfer_domestic is not None:
          self.non_money_transfer_domestic = non_money_transfer_domestic
        if online_gambling_fast_funds_cross_border is not None:
          self.online_gambling_fast_funds_cross_border = online_gambling_fast_funds_cross_border
        if online_gambling_fast_funds_domestic is not None:
          self.online_gambling_fast_funds_domestic = online_gambling_fast_funds_domestic
        if online_gambling_cross_border is not None:
          self.online_gambling_cross_border = online_gambling_cross_border
        if online_gambling_domestic is not None:
          self.online_gambling_domestic = online_gambling_domestic
        if domestic_participant is not None:
          self.domestic_participant = domestic_participant
        if cross_border_participant is not None:
          self.cross_border_participant = cross_border_participant

    @property
    def money_transfer_fast_funds_cross_border(self):
        """
        Gets the money_transfer_fast_funds_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if cross-border money transfer OCTs (fast push funds) are allowed. Possible values:   - `Y`   - `N` 

        :return: The money_transfer_fast_funds_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        :rtype: str
        """
        return self._money_transfer_fast_funds_cross_border

    @money_transfer_fast_funds_cross_border.setter
    def money_transfer_fast_funds_cross_border(self, money_transfer_fast_funds_cross_border):
        """
        Sets the money_transfer_fast_funds_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if cross-border money transfer OCTs (fast push funds) are allowed. Possible values:   - `Y`   - `N` 

        :param money_transfer_fast_funds_cross_border: The money_transfer_fast_funds_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        :type: str
        """

        self._money_transfer_fast_funds_cross_border = money_transfer_fast_funds_cross_border

    @property
    def money_transfer_fast_funds_domestic(self):
        """
        Gets the money_transfer_fast_funds_domestic of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if domestic money transfer OCTs (fast push funds) are allowed. Possible values:   - `Y`   - `N` 

        :return: The money_transfer_fast_funds_domestic of this InlineResponse2011PayoutInformationPushFunds.
        :rtype: str
        """
        return self._money_transfer_fast_funds_domestic

    @money_transfer_fast_funds_domestic.setter
    def money_transfer_fast_funds_domestic(self, money_transfer_fast_funds_domestic):
        """
        Sets the money_transfer_fast_funds_domestic of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if domestic money transfer OCTs (fast push funds) are allowed. Possible values:   - `Y`   - `N` 

        :param money_transfer_fast_funds_domestic: The money_transfer_fast_funds_domestic of this InlineResponse2011PayoutInformationPushFunds.
        :type: str
        """

        self._money_transfer_fast_funds_domestic = money_transfer_fast_funds_domestic

    @property
    def money_transfer_cross_border(self):
        """
        Gets the money_transfer_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if cross-border money transfer OCTs (push funds) are allowed. Possible values:   - `Y`   - `N` 

        :return: The money_transfer_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        :rtype: str
        """
        return self._money_transfer_cross_border

    @money_transfer_cross_border.setter
    def money_transfer_cross_border(self, money_transfer_cross_border):
        """
        Sets the money_transfer_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if cross-border money transfer OCTs (push funds) are allowed. Possible values:   - `Y`   - `N` 

        :param money_transfer_cross_border: The money_transfer_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        :type: str
        """

        self._money_transfer_cross_border = money_transfer_cross_border

    @property
    def money_transfer_domestic(self):
        """
        Gets the money_transfer_domestic of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if domestic money transfer OCTs (push funds) are allowed. Possible values:   - `Y`   - `N` 

        :return: The money_transfer_domestic of this InlineResponse2011PayoutInformationPushFunds.
        :rtype: str
        """
        return self._money_transfer_domestic

    @money_transfer_domestic.setter
    def money_transfer_domestic(self, money_transfer_domestic):
        """
        Sets the money_transfer_domestic of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if domestic money transfer OCTs (push funds) are allowed. Possible values:   - `Y`   - `N` 

        :param money_transfer_domestic: The money_transfer_domestic of this InlineResponse2011PayoutInformationPushFunds.
        :type: str
        """

        self._money_transfer_domestic = money_transfer_domestic

    @property
    def non_money_transfer_fast_funds_cross_border(self):
        """
        Gets the non_money_transfer_fast_funds_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if cross-border non-money transfer OCTs (fast push funds) are allowed. Possible values:   - `Y`   - `N` 

        :return: The non_money_transfer_fast_funds_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        :rtype: str
        """
        return self._non_money_transfer_fast_funds_cross_border

    @non_money_transfer_fast_funds_cross_border.setter
    def non_money_transfer_fast_funds_cross_border(self, non_money_transfer_fast_funds_cross_border):
        """
        Sets the non_money_transfer_fast_funds_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if cross-border non-money transfer OCTs (fast push funds) are allowed. Possible values:   - `Y`   - `N` 

        :param non_money_transfer_fast_funds_cross_border: The non_money_transfer_fast_funds_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        :type: str
        """

        self._non_money_transfer_fast_funds_cross_border = non_money_transfer_fast_funds_cross_border

    @property
    def non_money_transfer_fast_funds_domestic(self):
        """
        Gets the non_money_transfer_fast_funds_domestic of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if domestic non-money transfer OCTs (fast push funds) are allowed. Possible values:   - `Y`   - `N` 

        :return: The non_money_transfer_fast_funds_domestic of this InlineResponse2011PayoutInformationPushFunds.
        :rtype: str
        """
        return self._non_money_transfer_fast_funds_domestic

    @non_money_transfer_fast_funds_domestic.setter
    def non_money_transfer_fast_funds_domestic(self, non_money_transfer_fast_funds_domestic):
        """
        Sets the non_money_transfer_fast_funds_domestic of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if domestic non-money transfer OCTs (fast push funds) are allowed. Possible values:   - `Y`   - `N` 

        :param non_money_transfer_fast_funds_domestic: The non_money_transfer_fast_funds_domestic of this InlineResponse2011PayoutInformationPushFunds.
        :type: str
        """

        self._non_money_transfer_fast_funds_domestic = non_money_transfer_fast_funds_domestic

    @property
    def non_money_transfer_cross_border(self):
        """
        Gets the non_money_transfer_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if cross-border non-money transfer OCTs (push funds) are allowed. Possible values:   - `Y`   - `N` 

        :return: The non_money_transfer_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        :rtype: str
        """
        return self._non_money_transfer_cross_border

    @non_money_transfer_cross_border.setter
    def non_money_transfer_cross_border(self, non_money_transfer_cross_border):
        """
        Sets the non_money_transfer_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if cross-border non-money transfer OCTs (push funds) are allowed. Possible values:   - `Y`   - `N` 

        :param non_money_transfer_cross_border: The non_money_transfer_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        :type: str
        """

        self._non_money_transfer_cross_border = non_money_transfer_cross_border

    @property
    def non_money_transfer_domestic(self):
        """
        Gets the non_money_transfer_domestic of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if domestic non-money transfer OCTs (push funds) are allowed. Possible values:   - `Y`   - `N` 

        :return: The non_money_transfer_domestic of this InlineResponse2011PayoutInformationPushFunds.
        :rtype: str
        """
        return self._non_money_transfer_domestic

    @non_money_transfer_domestic.setter
    def non_money_transfer_domestic(self, non_money_transfer_domestic):
        """
        Sets the non_money_transfer_domestic of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if domestic non-money transfer OCTs (push funds) are allowed. Possible values:   - `Y`   - `N` 

        :param non_money_transfer_domestic: The non_money_transfer_domestic of this InlineResponse2011PayoutInformationPushFunds.
        :type: str
        """

        self._non_money_transfer_domestic = non_money_transfer_domestic

    @property
    def online_gambling_fast_funds_cross_border(self):
        """
        Gets the online_gambling_fast_funds_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if cross-border gambling OCTs (fast push funds) are allowed. Possible values:   - `Y`   - `N` 

        :return: The online_gambling_fast_funds_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        :rtype: str
        """
        return self._online_gambling_fast_funds_cross_border

    @online_gambling_fast_funds_cross_border.setter
    def online_gambling_fast_funds_cross_border(self, online_gambling_fast_funds_cross_border):
        """
        Sets the online_gambling_fast_funds_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if cross-border gambling OCTs (fast push funds) are allowed. Possible values:   - `Y`   - `N` 

        :param online_gambling_fast_funds_cross_border: The online_gambling_fast_funds_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        :type: str
        """

        self._online_gambling_fast_funds_cross_border = online_gambling_fast_funds_cross_border

    @property
    def online_gambling_fast_funds_domestic(self):
        """
        Gets the online_gambling_fast_funds_domestic of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if domestic gambling OCTs (fast push funds) are allowed. Possible values:   - `Y`   - `N` 

        :return: The online_gambling_fast_funds_domestic of this InlineResponse2011PayoutInformationPushFunds.
        :rtype: str
        """
        return self._online_gambling_fast_funds_domestic

    @online_gambling_fast_funds_domestic.setter
    def online_gambling_fast_funds_domestic(self, online_gambling_fast_funds_domestic):
        """
        Sets the online_gambling_fast_funds_domestic of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if domestic gambling OCTs (fast push funds) are allowed. Possible values:   - `Y`   - `N` 

        :param online_gambling_fast_funds_domestic: The online_gambling_fast_funds_domestic of this InlineResponse2011PayoutInformationPushFunds.
        :type: str
        """

        self._online_gambling_fast_funds_domestic = online_gambling_fast_funds_domestic

    @property
    def online_gambling_cross_border(self):
        """
        Gets the online_gambling_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if cross-border gambling OCTs (push funds) are allowed. Possible values:   - `Y`   - `N` 

        :return: The online_gambling_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        :rtype: str
        """
        return self._online_gambling_cross_border

    @online_gambling_cross_border.setter
    def online_gambling_cross_border(self, online_gambling_cross_border):
        """
        Sets the online_gambling_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if cross-border gambling OCTs (push funds) are allowed. Possible values:   - `Y`   - `N` 

        :param online_gambling_cross_border: The online_gambling_cross_border of this InlineResponse2011PayoutInformationPushFunds.
        :type: str
        """

        self._online_gambling_cross_border = online_gambling_cross_border

    @property
    def online_gambling_domestic(self):
        """
        Gets the online_gambling_domestic of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if domestic gambling OCTs (push funds) are allowed. Possible values:   - `Y`   - `N` 

        :return: The online_gambling_domestic of this InlineResponse2011PayoutInformationPushFunds.
        :rtype: str
        """
        return self._online_gambling_domestic

    @online_gambling_domestic.setter
    def online_gambling_domestic(self, online_gambling_domestic):
        """
        Sets the online_gambling_domestic of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if domestic gambling OCTs (push funds) are allowed. Possible values:   - `Y`   - `N` 

        :param online_gambling_domestic: The online_gambling_domestic of this InlineResponse2011PayoutInformationPushFunds.
        :type: str
        """

        self._online_gambling_domestic = online_gambling_domestic

    @property
    def domestic_participant(self):
        """
        Gets the domestic_participant of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if domestic OCTs (push funds) are allowed. Note: Supported only in US for domestic transactions involving Push Payments Gateway Service(PPGS). Possible values:   - `true`   - `false` 

        :return: The domestic_participant of this InlineResponse2011PayoutInformationPushFunds.
        :rtype: str
        """
        return self._domestic_participant

    @domestic_participant.setter
    def domestic_participant(self, domestic_participant):
        """
        Sets the domestic_participant of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if domestic OCTs (push funds) are allowed. Note: Supported only in US for domestic transactions involving Push Payments Gateway Service(PPGS). Possible values:   - `true`   - `false` 

        :param domestic_participant: The domestic_participant of this InlineResponse2011PayoutInformationPushFunds.
        :type: str
        """

        self._domestic_participant = domestic_participant

    @property
    def cross_border_participant(self):
        """
        Gets the cross_border_participant of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if cross-border OCTs (push funds) are allowed. Note: Supported only in US for cross-border transactions involving Push Payments Gateway Service(PPGS). Possible values:   - `true`   - `false` 

        :return: The cross_border_participant of this InlineResponse2011PayoutInformationPushFunds.
        :rtype: str
        """
        return self._cross_border_participant

    @cross_border_participant.setter
    def cross_border_participant(self, cross_border_participant):
        """
        Sets the cross_border_participant of this InlineResponse2011PayoutInformationPushFunds.
        This field indicates if cross-border OCTs (push funds) are allowed. Note: Supported only in US for cross-border transactions involving Push Payments Gateway Service(PPGS). Possible values:   - `true`   - `false` 

        :param cross_border_participant: The cross_border_participant of this InlineResponse2011PayoutInformationPushFunds.
        :type: str
        """

        self._cross_border_participant = cross_border_participant

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse2011PayoutInformationPushFunds):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
