# coding: utf-8

"""
    CyberSource Merged Spec

    All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from pprint import pformat
from six import iteritems
import re


class PushFunds201ResponsePaymentInformationTokenizedCard(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'assurance_method': 'str'
    }

    attribute_map = {
        'assurance_method': 'assuranceMethod'
    }

    def __init__(self, assurance_method=None):
        """
        PushFunds201ResponsePaymentInformationTokenizedCard - a model defined in Swagger
        """

        self._assurance_method = None

        if assurance_method is not None:
          self.assurance_method = assurance_method

    @property
    def assurance_method(self):
        """
        Gets the assurance_method of this PushFunds201ResponsePaymentInformationTokenizedCard.
        Confidence level of the tokenization. This value is assigned by the token service provider.  Valid Values:  Spaces (No value set)  00 = No issuer ID&V  10 = Card issuer account verification  11 = Card issuer interactive cardholder authentication - 1 factor  12 = Card issuer interactive cardholder authentication - 2 factor  13 = Card issuer risk oriented non-interactive cardholder authentication  14 = Card issuer asserted authentication 

        :return: The assurance_method of this PushFunds201ResponsePaymentInformationTokenizedCard.
        :rtype: str
        """
        return self._assurance_method

    @assurance_method.setter
    def assurance_method(self, assurance_method):
        """
        Sets the assurance_method of this PushFunds201ResponsePaymentInformationTokenizedCard.
        Confidence level of the tokenization. This value is assigned by the token service provider.  Valid Values:  Spaces (No value set)  00 = No issuer ID&V  10 = Card issuer account verification  11 = Card issuer interactive cardholder authentication - 1 factor  12 = Card issuer interactive cardholder authentication - 2 factor  13 = Card issuer risk oriented non-interactive cardholder authentication  14 = Card issuer asserted authentication 

        :param assurance_method: The assurance_method of this PushFunds201ResponsePaymentInformationTokenizedCard.
        :type: str
        """

        self._assurance_method = assurance_method

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PushFunds201ResponsePaymentInformationTokenizedCard):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
