# coding: utf-8

"""
    CyberSource Merged Spec

    All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from pprint import pformat
from six import iteritems
import re


class Tmsv2TokenizedCardMetadataIssuer(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'short_description': 'str',
        'long_description': 'str',
        'email': 'str',
        'phone_number': 'str',
        'url': 'str',
        'privacy_policy_url': 'str',
        'capabilities': 'Tmsv2TokenizedCardMetadataIssuerCapabilities',
        'bank_applications': 'list[Tmsv2TokenizedCardMetadataIssuerBankApplications]'
    }

    attribute_map = {
        'name': 'name',
        'short_description': 'shortDescription',
        'long_description': 'longDescription',
        'email': 'email',
        'phone_number': 'phoneNumber',
        'url': 'url',
        'privacy_policy_url': 'privacyPolicyUrl',
        'capabilities': 'capabilities',
        'bank_applications': 'bankApplications'
    }

    def __init__(self, name=None, short_description=None, long_description=None, email=None, phone_number=None, url=None, privacy_policy_url=None, capabilities=None, bank_applications=None):
        """
        Tmsv2TokenizedCardMetadataIssuer - a model defined in Swagger
        """

        self._name = None
        self._short_description = None
        self._long_description = None
        self._email = None
        self._phone_number = None
        self._url = None
        self._privacy_policy_url = None
        self._capabilities = None
        self._bank_applications = None

        if name is not None:
          self.name = name
        if short_description is not None:
          self.short_description = short_description
        if long_description is not None:
          self.long_description = long_description
        if email is not None:
          self.email = email
        if phone_number is not None:
          self.phone_number = phone_number
        if url is not None:
          self.url = url
        if privacy_policy_url is not None:
          self.privacy_policy_url = privacy_policy_url
        if capabilities is not None:
          self.capabilities = capabilities
        if bank_applications is not None:
          self.bank_applications = bank_applications

    @property
    def name(self):
        """
        Gets the name of this Tmsv2TokenizedCardMetadataIssuer.
        Issuer name. 

        :return: The name of this Tmsv2TokenizedCardMetadataIssuer.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Tmsv2TokenizedCardMetadataIssuer.
        Issuer name. 

        :param name: The name of this Tmsv2TokenizedCardMetadataIssuer.
        :type: str
        """

        self._name = name

    @property
    def short_description(self):
        """
        Gets the short_description of this Tmsv2TokenizedCardMetadataIssuer.
        Short description of the card. 

        :return: The short_description of this Tmsv2TokenizedCardMetadataIssuer.
        :rtype: str
        """
        return self._short_description

    @short_description.setter
    def short_description(self, short_description):
        """
        Sets the short_description of this Tmsv2TokenizedCardMetadataIssuer.
        Short description of the card. 

        :param short_description: The short_description of this Tmsv2TokenizedCardMetadataIssuer.
        :type: str
        """

        self._short_description = short_description

    @property
    def long_description(self):
        """
        Gets the long_description of this Tmsv2TokenizedCardMetadataIssuer.
        Long description of the card. 

        :return: The long_description of this Tmsv2TokenizedCardMetadataIssuer.
        :rtype: str
        """
        return self._long_description

    @long_description.setter
    def long_description(self, long_description):
        """
        Sets the long_description of this Tmsv2TokenizedCardMetadataIssuer.
        Long description of the card. 

        :param long_description: The long_description of this Tmsv2TokenizedCardMetadataIssuer.
        :type: str
        """

        self._long_description = long_description

    @property
    def email(self):
        """
        Gets the email of this Tmsv2TokenizedCardMetadataIssuer.
        Issuer customer service email address. 

        :return: The email of this Tmsv2TokenizedCardMetadataIssuer.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this Tmsv2TokenizedCardMetadataIssuer.
        Issuer customer service email address. 

        :param email: The email of this Tmsv2TokenizedCardMetadataIssuer.
        :type: str
        """

        self._email = email

    @property
    def phone_number(self):
        """
        Gets the phone_number of this Tmsv2TokenizedCardMetadataIssuer.
        Issuer customer service phone number. 

        :return: The phone_number of this Tmsv2TokenizedCardMetadataIssuer.
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """
        Sets the phone_number of this Tmsv2TokenizedCardMetadataIssuer.
        Issuer customer service phone number. 

        :param phone_number: The phone_number of this Tmsv2TokenizedCardMetadataIssuer.
        :type: str
        """

        self._phone_number = phone_number

    @property
    def url(self):
        """
        Gets the url of this Tmsv2TokenizedCardMetadataIssuer.
        Issuer customer service url. 

        :return: The url of this Tmsv2TokenizedCardMetadataIssuer.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """
        Sets the url of this Tmsv2TokenizedCardMetadataIssuer.
        Issuer customer service url. 

        :param url: The url of this Tmsv2TokenizedCardMetadataIssuer.
        :type: str
        """

        self._url = url

    @property
    def privacy_policy_url(self):
        """
        Gets the privacy_policy_url of this Tmsv2TokenizedCardMetadataIssuer.
        Issuer privacy policy url. 

        :return: The privacy_policy_url of this Tmsv2TokenizedCardMetadataIssuer.
        :rtype: str
        """
        return self._privacy_policy_url

    @privacy_policy_url.setter
    def privacy_policy_url(self, privacy_policy_url):
        """
        Sets the privacy_policy_url of this Tmsv2TokenizedCardMetadataIssuer.
        Issuer privacy policy url. 

        :param privacy_policy_url: The privacy_policy_url of this Tmsv2TokenizedCardMetadataIssuer.
        :type: str
        """

        self._privacy_policy_url = privacy_policy_url

    @property
    def capabilities(self):
        """
        Gets the capabilities of this Tmsv2TokenizedCardMetadataIssuer.

        :return: The capabilities of this Tmsv2TokenizedCardMetadataIssuer.
        :rtype: Tmsv2TokenizedCardMetadataIssuerCapabilities
        """
        return self._capabilities

    @capabilities.setter
    def capabilities(self, capabilities):
        """
        Sets the capabilities of this Tmsv2TokenizedCardMetadataIssuer.

        :param capabilities: The capabilities of this Tmsv2TokenizedCardMetadataIssuer.
        :type: Tmsv2TokenizedCardMetadataIssuerCapabilities
        """

        self._capabilities = capabilities

    @property
    def bank_applications(self):
        """
        Gets the bank_applications of this Tmsv2TokenizedCardMetadataIssuer.

        :return: The bank_applications of this Tmsv2TokenizedCardMetadataIssuer.
        :rtype: list[Tmsv2TokenizedCardMetadataIssuerBankApplications]
        """
        return self._bank_applications

    @bank_applications.setter
    def bank_applications(self, bank_applications):
        """
        Sets the bank_applications of this Tmsv2TokenizedCardMetadataIssuer.

        :param bank_applications: The bank_applications of this Tmsv2TokenizedCardMetadataIssuer.
        :type: list[Tmsv2TokenizedCardMetadataIssuerBankApplications]
        """

        self._bank_applications = bank_applications

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Tmsv2TokenizedCardMetadataIssuer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
